name: Check

on:
  push:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Check & Push
      uses: docker/build-push-action@v1 # https://github.com/docker/build-push-action
      with:
        dockerfile: Dockerfile.dev
        repository: yukijs/levia
        tags: dev
        push: false